### ISSUE TITLE
add captions to videos

### ISSUE THREAD

**Issue by jlengstorf** [netlify/explorers#423]
we have transcripts, but it looks like we need a [VTT file added in a `<track>` element](https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Adding_captions_and_subtitles_to_HTML5_video) to get this actually working in the videos

we can [auto-generate VTTs with Cloudinary](https://cloudinary.com/documentation/google_ai_video_transcription_addon#cloudinary_transcript_files), but that'll have all the AI issues we've come to know and love about captioning

if we can get the transcripts in VTT, that would be ideal

**Comment by bencodezen** [comment]
Validated concept, but we have an issue with bumper shifting the timestamp on when the captions occur.
