### ISSUE TITLE
Plan swag store integration

### ISSUE THREAD

**Issue by tzmanics** [netlify/explorers#454]
- swag plan: who gets what when
  - sticker pack for mission
  - x for y where we can build on `swag` for `achievement`
- path plan: how do users get from explorers site to the swag store (do we or do we just get their info and send them goodies)
  - just generate a 1-time coupon code from shopify, button on their redeem button will have their code when they go to swag store. check if coupon code is valid and if ! then remove button or show 'reedemed, congrats'
- info plan: all info thru swag store
- tracking plan: do we keep track of who gets what when (collect them all adventure)
who gets swag when
  - using activity hub so that we make jamstack explorer achievements 
  
??? How do we make sure we're not hitting the Shopify API on each dashboard load ???
  @jlengstorf to review, possibly add redemption code to achievement in activity hub and when load dashboard check if achievement unlocked && if code exists && if it's redeemed

**Comment by tzmanics** [comment]
options
- just generate a 1-time coupon code from shopify, button on their redeem button will have their code when they go to swag store.

**Comment by tzmanics** [comment]
@jlengstorf would u say this plan is fleshed out now?

**Comment by philhawksworth** [comment]
Workflow:
https://miro.com/app/board/o9J_lWmoARA=/

**Comment by jlengstorf** [comment]
@tzmanics I think we're all on the same page now. I think the pairing tomorrow should get us all the way through shared context, at which point this is probably safe to close
