### ISSUE TITLE
Record in the Activity Hub that the completed-a-mission achievement has been attained by a user

### ISSUE THREAD

**Issue by philhawksworth** [netlify/explorers#471]
A serverless function should exist for every achievement we wish to register for a user.
These functions will be registered as webhooks in Hasura to be fired when write events happen in the Activity hub. 

This issue is to track that:
- A function exists to test for the attainment of the `completed-a-mission` achievement.
- The function, when invoked should: 
  - determine of all stages of a mission have been completed by a given user (this should be done by activity checks in explorers)
  - if more than zero missions was have been completed, this should be entered into the achievements table in Hasura
  
In future, additional, similar functions will be registered in the same way to perform the logic for determining if other achievements have been satisfied.

**Comment by philhawksworth** [comment]
Flow for reference: https://miro.com/app/board/o9J_lWmoARA=/

**Comment by tzmanics** [comment]
Work on this being done on this branch (PR #468 )
