### ISSUE TITLE
[Achievement listing] Achievement removed from profile after reward claim

### ISSUE THREAD

**Issue by philhawksworth** [netlify/explorers#504]
**What needs fixed?**

After successfully (🎉) claiming my sticker reward, I notice on my next visit to my profile page that no achievments were listed.

**How do you propose it should be fixed?**

The desired result is that claimed rewards are visible in the user's profile and marked as "claimed" in their achievements listing.

As described [here](https://github.com/netlify/explorers/issues/481#issuecomment-806570779)

**Comment by kenny-io** [comment]
@philhawksworth this functionality is currently available. Any claimed reward is marked "CLAIMED" and is still available in the profile page. See my test from feature/rewards preview https://608060b8937435000854df58--explorers.netlify.app/profile

![image](https://user-images.githubusercontent.com/20874031/115692957-82bcad80-a370-11eb-835a-6508779ee653.png)

Curious if this is not the case for anyone else?
