### ISSUE TITLE
[broken thing] Pretty please add written transcript to Serverless Functions mission

### ISSUE THREAD

**Issue by MelanieCrissey** [netlify/explorers#519]
**What needs fixed?**
Developer on Twitter reported that written transcripts are missing from each section of this mission: https://explorers.netlify.com/learn/up-and-running-with-serverless-functions

https://twitter.com/DEGoodmanWilson/status/1453739458289881089?s=20

**How do you propose it should be fixed?**
This would be better if it followed the same transcription style as other serverless missions, like this one: https://explorers.netlify.com/learn/angular-in-the-jamstack/intro

Once we get it added, we should follow up on the Twitter thread to confirm it's corrected and close the loop!

Note: while we're in there, we might want to do a quick spot check to confirm all of the other missions have written transcripts, too!

**Comment by bencodezen** [comment]
This should be resolved now! I'll audit the rest of the missions to ensure it's not a problem, but we're good on this mission now!
